### ISSUE TITLE
AttributeError: 'Anymal' object has no attribute 'terrain'

### ISSUE THREAD

**Issue by YoontaeCho** [MarkFzp/Deep-Whole-Body-Control#7]
Hi, thank you for your great work!
While trying to reproducing your work, I got some error while executing `python train.py --task=anymal_c_flat`, which is the method you have mentioned in readme.
Full error messages are as follows:
```
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    train(args)
  File "train.py", line 51, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/ytcho/workspace/Deep-Whole-Body-Control/legged_gym/legged_gym/utils/task_registry.py", line 106, in make_env
    headless=args.headless)
  File "/home/ytcho/workspace/Deep-Whole-Body-Control/legged_gym/legged_gym/envs/anymal_c/anymal.py", line 49, in __init__
    super().__init__(cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/ytcho/workspace/Deep-Whole-Body-Control/legged_gym/legged_gym/envs/base/legged_robot.py", line 71, in __init__
    super().__init__(self.cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/ytcho/workspace/Deep-Whole-Body-Control/legged_gym/legged_gym/envs/base/base_task.py", line 86, in __init__
    self.create_sim()
  File "/home/ytcho/workspace/Deep-Whole-Body-Control/legged_gym/legged_gym/envs/base/legged_robot.py", line 237, in create_sim
    self._create_ground_plane()
  File "/home/ytcho/workspace/Deep-Whole-Body-Control/legged_gym/legged_gym/envs/base/legged_robot.py", line 582, in _create_ground_plane
    self.height_samples = torch.zeros(self.terrain.tot_rows, self.terrain.tot_cols).to(self.device)
AttributeError: 'Anymal' object has no attribute 'terrain'
```
Is this a bug, or I missed something(e.g. missing arguments)?
Thank you in advance.

**Comment by YoontaeCho** [comment]
Issue resolved, after passing the task argument "--task widowGo1", which is the default task
`python train.py --task widowGo1`
